### ISSUE TITLE
Know issues section?

### ISSUE THREAD

**Issue by codykonior** [olivierlacan/keep-a-changelog#248] opened 2018-07-26 11:53 UTC
Would it be useful for a Changelog to have a known issues section?

For example, I'm committing a change and know it's not perfect, and will break under these situations to be remedied later?

**Comment by olivierlacan** [comment] 2018-11-01 03:12
That's a good idea but I sort of expect that to be within a `README`. That's not really the job of a changelog in my mind. But as you said, if a release includes things that don't address a known issue, there might be a good case for this. Can you gather some existing examples maybe?

**Comment by davidak** [comment] 2018-11-20 19:15
Duplicate of https://github.com/olivierlacan/keep-a-changelog/issues/89

**Closed** 2023-03-07 04:36 UTC
